[package]
name = "hoi_mod_uploader_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.11"
jomini = { version = "0.26.0", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
steamworks = "0.11.0"
